//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Partyme.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Partyme.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Añadir.
        /// </summary>
        public static string appbaramigos1 {
            get {
                return ResourceManager.GetString("appbaramigos1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invitar SMS.
        /// </summary>
        public static string appbaramigos2 {
            get {
                return ResourceManager.GetString("appbaramigos2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invitar MAIL.
        /// </summary>
        public static string appbaramigos3 {
            get {
                return ResourceManager.GetString("appbaramigos3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Notificaciones.
        /// </summary>
        public static string appbaramigos4 {
            get {
                return ResourceManager.GetString("appbaramigos4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a agregar.
        /// </summary>
        public static string AppBarButtonText {
            get {
                return ResourceManager.GetString("AppBarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Locales.
        /// </summary>
        public static string appbarmap1 {
            get {
                return ResourceManager.GetString("appbarmap1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eventos.
        /// </summary>
        public static string appbarmap2 {
            get {
                return ResourceManager.GetString("appbarmap2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ofertas.
        /// </summary>
        public static string appbarmap3 {
            get {
                return ResourceManager.GetString("appbarmap3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Personas.
        /// </summary>
        public static string appbarmap4 {
            get {
                return ResourceManager.GetString("appbarmap4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Elemento de menú.
        /// </summary>
        public static string AppBarMenuItemText {
            get {
                return ResourceManager.GetString("AppBarMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar Cambios.
        /// </summary>
        public static string appbarperfil1 {
            get {
                return ResourceManager.GetString("appbarperfil1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fotos.
        /// </summary>
        public static string appbarperfil2 {
            get {
                return ResourceManager.GetString("appbarperfil2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Favoritos y vip.
        /// </summary>
        public static string appbarperfil3 {
            get {
                return ResourceManager.GetString("appbarperfil3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Notificaciones.
        /// </summary>
        public static string appbarplan1 {
            get {
                return ResourceManager.GetString("appbarplan1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Capturar QR.
        /// </summary>
        public static string appbarplan2 {
            get {
                return ResourceManager.GetString("appbarplan2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a En Curso.
        /// </summary>
        public static string appbarservicios1 {
            get {
                return ResourceManager.GetString("appbarservicios1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Historico.
        /// </summary>
        public static string appbarservicios2 {
            get {
                return ResourceManager.GetString("appbarservicios2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SocialAppV2.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La aplicación no tiene acceso a internet o hay un fallo en la conexión del dispositivo.  La aplicación se cerrara..
        /// </summary>
        public static string conexion {
            get {
                return ResourceManager.GetString("conexion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ERROR DE CONEXIÓN.
        /// </summary>
        public static string conexioncab {
            get {
                return ResourceManager.GetString("conexioncab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a error json.
        /// </summary>
        public static string errorjson {
            get {
                return ResourceManager.GetString("errorjson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eventos.
        /// </summary>
        public static string eventoslist {
            get {
                return ResourceManager.GetString("eventoslist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gente.
        /// </summary>
        public static string gentelist {
            get {
                return ResourceManager.GetString("gentelist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Locales.
        /// </summary>
        public static string localeslist {
            get {
                return ResourceManager.GetString("localeslist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PERMISO DE UBICACIÓN.
        /// </summary>
        public static string loccab {
            get {
                return ResourceManager.GetString("loccab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La aplicación necesita permiso para usar acceder a la localización del usuario para algunas funciones. ¿Quiere qué la aplicación pueda acceder a su ubicación?.
        /// </summary>
        public static string locconsent {
            get {
                return ResourceManager.GetString("locconsent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No ha elejido su sexo, para crear el perfil debe elegir sexo..
        /// </summary>
        public static string nosexo {
            get {
                return ResourceManager.GetString("nosexo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ELIJA SEXO.
        /// </summary>
        public static string nosexocab {
            get {
                return ResourceManager.GetString("nosexocab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ofertas.
        /// </summary>
        public static string ofertaslist {
            get {
                return ResourceManager.GetString("ofertaslist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mapa.
        /// </summary>
        public static string pivot1 {
            get {
                return ResourceManager.GetString("pivot1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mis Planes.
        /// </summary>
        public static string pivot2 {
            get {
                return ResourceManager.GetString("pivot2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Amigos.
        /// </summary>
        public static string pivot3 {
            get {
                return ResourceManager.GetString("pivot3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Servicios.
        /// </summary>
        public static string pivot4 {
            get {
                return ResourceManager.GetString("pivot4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Perfil.
        /// </summary>
        public static string pivot5 {
            get {
                return ResourceManager.GetString("pivot5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Preferencias.
        /// </summary>
        public static string pivot6 {
            get {
                return ResourceManager.GetString("pivot6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Info.
        /// </summary>
        public static string pivotdetloc1 {
            get {
                return ResourceManager.GetString("pivotdetloc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ofertas.
        /// </summary>
        public static string pivotdetloc2 {
            get {
                return ResourceManager.GetString("pivotdetloc2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fiestas.
        /// </summary>
        public static string pivotdetloc3 {
            get {
                return ResourceManager.GetString("pivotdetloc3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fotos.
        /// </summary>
        public static string pivotdetloc4 {
            get {
                return ResourceManager.GetString("pivotdetloc4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a es-es.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valor de propiedad en tiempo de ejecución de ejemplo.
        /// </summary>
        public static string SampleProperty {
            get {
                return ResourceManager.GetString("SampleProperty", resourceCulture);
            }
        }
    }
}
